import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "utils/AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


async function getseesion(){
  return await getServerSession(authOptions)
}

export default async function RootLayout({ children }) {

  const session = await getseesion();
  return (
    <html lang="en">
      <head>
    <link rel="icon" href="/logoico.ico" style={{color:"white"}} sizes="any" />
      <title>Chalkpad</title>
      </head>
      <body className={inter.className}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
